import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // ── Core data (always seeded) ─────────────────────────────────────────────

  const [newnham, senecaYork] = await Promise.all([
    prisma.campus.upsert({
      where: { campusName: 'Newnham' },
      update: {},
      create: {
        campusName: 'Newnham',
        address: '1750 Finch Ave E, Toronto, ON M2J 2X5',
        retentionDays: 30,
      },
    }),
    prisma.campus.upsert({
      where: { campusName: 'Seneca@York' },
      update: {},
      create: {
        campusName: 'Seneca@York',
        address: '70 The Pond Rd, Toronto, ON M3J 3M6',
        retentionDays: 30,
      },
    }),
    prisma.campus.upsert({
      where: { campusName: 'King' },
      update: {},
      create: {
        campusName: 'King',
        address: '13990 Dufferin St, King City, ON L7B 1B3',
        retentionDays: 30,
      },
    }),
    prisma.campus.upsert({
      where: { campusName: 'Peterborough' },
      update: {},
      create: {
        campusName: 'Peterborough',
        address: '1717 Lansdowne St W, Peterborough, ON K9J 7B1',
        retentionDays: 30,
      },
    }),
  ]);

  console.log('Campuses: Newnham, Seneca@York, King, Peterborough');

  const adminHash = await bcrypt.hash('Admin@1234', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@myseneca.ca' },
    update: {},
    create: {
      campusId: newnham.campusId,
      email: 'admin@myseneca.ca',
      username: 'admin',
      passwordHash: adminHash,
      role: 'admin',
      firstName: 'System',
      lastName: 'Admin',
      isActive: true,
    },
  });

  console.log(`Admin: ${admin.email} / Admin@1234`);

  // ── Dev sample data (skipped in production) ───────────────────────────────

  if (process.env.NODE_ENV === 'production') {
    console.log('Skipping dev sample data (production)');
    return;
  }

  const testHash = await bcrypt.hash('Test1234!', 12);

  const [alice, bob, carol] = await Promise.all([
    prisma.user.upsert({
      where: { email: 'alice@myseneca.ca' },
      update: {},
      create: {
        campusId: newnham.campusId,
        email: 'alice@myseneca.ca',
        username: 'alice',
        passwordHash: testHash,
        role: 'student',
        firstName: 'Alice',
        lastName: 'Smith',
        studentNumber: BigInt('123456789'),
        isActive: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'bob@myseneca.ca' },
      update: {},
      create: {
        campusId: senecaYork.campusId,
        email: 'bob@myseneca.ca',
        username: 'bob',
        passwordHash: testHash,
        role: 'student',
        firstName: 'Bob',
        lastName: 'Kim',
        studentNumber: BigInt('987654321'),
        isActive: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'carol@myseneca.ca' },
      update: {},
      create: {
        campusId: newnham.campusId,
        email: 'carol@myseneca.ca',
        username: 'carol',
        passwordHash: testHash,
        role: 'security',
        firstName: 'Carol',
        lastName: 'Jones',
        isActive: true,
      },
    }),
  ]);

  console.log(
    'Dev users: alice, bob (students) + carol (security) / Test1234!'
  );

  // Sample report link generated by carol
  const reportLink = await prisma.reportLink.upsert({
    where: { token: 'dev-sample-token-abc123' },
    update: {},
    create: {
      token: 'dev-sample-token-abc123',
      generatedBy: carol.userId,
      campusId: newnham.campusId,
      expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    },
  });

  // Sample found item report submitted by alice via the report link
  const existingReport = await prisma.foundItemReport.findFirst({
    where: { reportLinkId: reportLink.linkId, finderId: alice.userId },
  });
  if (!existingReport) {
    await prisma.foundItemReport.create({
      data: {
        reportLinkId: reportLink.linkId,
        finderId: alice.userId,
        itemDescription: 'White AirPods Pro case with small sticker',
        category: 'electronics',
        locationFound: 'Near Tim Hortons, Newnham Campus',
        dateFound: new Date('2026-05-10'),
        additionalNotes: 'Found it on a bench outside Tim Hortons',
        status: 'submitted',
      },
    });
  }

  // Sample item registered by carol
  const existingItem = await prisma.item.findFirst({
    where: { registeredBy: carol.userId, title: 'AirPods Pro - White Case' },
  });
  if (!existingItem) {
    await prisma.item.create({
      data: {
        campusId: newnham.campusId,
        category: 'electronics',
        title: 'AirPods Pro - White Case',
        descriptionPublic: 'White AirPods Pro case with sticker',
        descriptionInternal:
          'White AirPods Pro case with a small round sticker on lid.',
        color: 'white',
        brand: 'Apple',
        locationFound: 'Near Tim Hortons, Newnham Campus',
        dateFound: new Date('2026-05-10'),
        status: 'stored',
        registeredBy: carol.userId,
        retentionExpiryDate: new Date('2026-06-09'),
      },
    });
  }

  // Sample claim submitted by bob
  const existingClaim = await prisma.claim.findFirst({
    where: { studentId: bob.userId, category: 'electronics' },
  });
  if (!existingClaim) {
    await prisma.claim.create({
      data: {
        studentId: bob.userId,
        campusId: newnham.campusId,
        category: 'electronics',
        description:
          'Lost my AirPods Pro with white case. Has a small round sticker on the lid.',
        dateLost: new Date('2026-05-10'),
        locationLost: 'Near Tim Hortons or the library, Newnham Campus',
        status: 'submitted',
      },
    });
  }

  console.log('Dev sample data: report link, found report, item, claim');
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
