-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
-- FoundIt Sample Data (for development/testing)
-- Run AFTER seed.sql
-- Tables: campus, "user", report_link, found_item_report, item, claim
-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+


-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
-- SAMPLE USERS
-- password for all: Test1234! (bcrypt)
-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

INSERT INTO "user" (email, username, password_hash, role, first_name, last_name, student_number, campus_id)
VALUES
    (
        'alice@myseneca.ca',
        'alice',
        '$2b$12$samplehashALICE00000000000000000000000000000000000000000',
        'student',
        'Alice', 'Smith',
        '123456789',
        (SELECT campus_id FROM campus WHERE campus_name = 'Newnham')
    ),
    (
        'bob@myseneca.ca',
        'bob',
        '$2b$12$samplehashBOB000000000000000000000000000000000000000000',
        'student',
        'Bob', 'Kim',
        '987654321',
        (SELECT campus_id FROM campus WHERE campus_name = 'Seneca@York')
    )
ON CONFLICT (email) DO NOTHING;

INSERT INTO "user" (email, username, password_hash, role, first_name, last_name, employee_id, campus_id)
VALUES
    (
        'carol@senecapolytechnic.ca',
        'carol',
        '$2b$12$samplehashCAROL0000000000000000000000000000000000000000',
        'security',
        'Carol', 'Jones',
        'EMP-001',
        (SELECT campus_id FROM campus WHERE campus_name = 'Newnham')
    )
ON CONFLICT (email) DO NOTHING;


-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
-- SAMPLE REPORT LINK (QR code link generated by security staff)
-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

INSERT INTO report_link (token, generated_by, campus_id, expires_at)
VALUES (
    'sample-token-abc123',
    (SELECT user_id FROM "user" WHERE email = 'carol@senecapolytechnic.ca'),
    (SELECT campus_id FROM campus WHERE campus_name = 'Newnham'),
    NOW() + INTERVAL '7 days'
)
ON CONFLICT (token) DO NOTHING;


-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
-- SAMPLE FOUND ITEM REPORT (submitted by student via QR link)
-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

INSERT INTO found_item_report (report_link_id, finder_id, item_description, category, location_found, date_found, additional_notes, status)
VALUES (
    (SELECT link_id FROM report_link WHERE token = 'sample-token-abc123'),
    (SELECT user_id FROM "user" WHERE email = 'alice@myseneca.ca'),
    'White AirPods Pro case with small sticker',
    'electronics',
    'Near Tim Hortons, Newnham Campus',
    '2026-05-10',
    'Found it on a bench outside Tim Hortons',
    'submitted'
)
ON CONFLICT DO NOTHING;


-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
-- SAMPLE ITEM (registered by security staff)
-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

INSERT INTO item (campus_id, category, title, description_public, description_internal, color, brand, location_found, date_found, status, registered_by, retention_expiry_date)
VALUES (
    (SELECT campus_id FROM campus WHERE campus_name = 'Newnham'),
    'electronics',
    'AirPods Pro - White Case',
    'White AirPods Pro case with sticker',
    'White AirPods Pro case with a small round sticker on lid. Serial number partially visible.',
    'white',
    'Apple',
    'Near Tim Hortons, Newnham Campus',
    '2026-05-10',
    'stored',
    (SELECT user_id FROM "user" WHERE email = 'carol@senecapolytechnic.ca'),
    '2026-06-09'
)
ON CONFLICT DO NOTHING;


-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
-- SAMPLE CLAIM (submitted by student)
-- +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

INSERT INTO claim (student_id, campus_id, category, description, date_lost, location_lost, status)
VALUES (
    (SELECT user_id FROM "user" WHERE email = 'bob@myseneca.ca'),
    (SELECT campus_id FROM campus WHERE campus_name = 'Newnham'),
    'electronics',
    'Lost my AirPods Pro with white case. Has a small round sticker on the lid. Bought in 2024.',
    '2026-05-10',
    'Near Tim Hortons or the library, Newnham Campus',
    'submitted'
)
ON CONFLICT DO NOTHING;
